server:
  port: 8080

#mbatis配置
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.xz.parking.entity
  configuration:
    #开启自动驼峰命名规则映射
    map-underscore-to-camel-case: true
    #打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#mysql配置
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/parking-lot?useUnicode=true&characterUnicoding=UTF-8
    username: root
    password: xzlyf297
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource # 配置当前要使用的数据源的操作类型
    dbcp2:
      min-idle: 5                                   # 数据库连接池的最小维持连接数
      initial-size: 5                               # 初始化提供的连接数
      max-total: 20                                  # 最大的连接数
      max-wait-millis: 200                         # 等待连接获取的最大超时时间

  #thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    cache: false
  #静态资源配置
  mvc:
    static-path-pattern: /static/**
  #热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  jackson:
    # 设置属性命名策略,对应jackson下PropertyNamingStrategy中的常量值，SNAKE_CASE-返回的json驼峰式转下划线，json body下划线传到后端自动转驼峰式
    property-naming-strategy: SNAKE_CASE
    # 全局设置@JsonFormat的格式pattern
    date-format: yyyy-MM-dd
    # 当地时区
    locale: zh
    # 设置全局时区
    time-zone: GMT+8
    # 常用，全局设置pojo或被@JsonInclude注解的属性的序列化方式
    default-property-inclusion: ALWAYS #不为空的属性才会序列化,具体属性可看JsonInclude.Include

#分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  params: count=countSql
  support-methods-arguments: true
